### ISSUE TITLE
followed instructions: bad substitution

### ISSUE THREAD

**Issue by jason-tung** [SimonBerens/SubmissionScript#1]
Bash version:
GNU bash, version 5.0.2(1)-release (x86_64-apple-darwin18.2.0)

Jasons-MacBook-Pro:graphics jason$ cd picmaker/
README.md
Jasons-MacBook-Pro:picmaker jason$ submit
picmaker	tmp
mkdir: tmp: File exists
picmaker
fatal: destination path 'picmaker' already exists and is not an empty directory.
README.md	diepCi		leongAl		nahianSa	wu_edwin
aschJa		hasanAh		linVi		peci_rubin	xia_sophia
aseerSa		jiangDa		lin_victor	scheinbergRe	zhouGa
berensSi	lamAn		mohriCl		tanSt
-bash: ${fname,,}: bad substitution
Jasons-MacBook-Pro:5 jason$

**Comment by SimonBerens** [comment]
Solution: use ubuntu

**Comment by jason-tung** [comment]
thank u it worked.
